### ISSUE TITLE
#banner:before on documentation is too wide

### ISSUE THREAD

**Issue by willox** [brantleye/grylls#1]
The 'before' of the banner element appears to be 16px wider than the browser window, I think this is caused by:

```css
#banner:before {
    ...
    margin-left: -8px;
    padding-right: 16px;
    ...
}
```

I don't know if the correct solution would be to remove both properties, change the padding-right property to be 8px or something else entirely.
It looks like this was added originally to counteract some padding the banner had, but it appears to have none now.
